# Generated by Django 3.2.2 on 2021-05-26 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Enter Payment Method')),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Add Type')),
                ('entry_date', models.DateField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.service', verbose_name='Choose Service')),
            ],
            options={
                'unique_together': {('service', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Enter Title')),
                ('description', models.TextField(unique=True, verbose_name='Enter Description')),
                ('url', models.URLField(unique=True, verbose_name='Website URL')),
                ('image', models.ImageField(upload_to='', verbose_name='Upload Image')),
            ],
            options={
                'unique_together': {('title', 'url')},
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('remark', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('only_date', models.DateField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='web.payment', verbose_name='Payment Method')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service', to='web.service', verbose_name='Choose Service')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.type', verbose_name='Choose Type')),
            ],
        ),
    ]
