# Generated by Django 3.2.2 on 2021-07-17 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_type_description'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='type',
            unique_together={('service', 'name', 'description')},
        ),
    ]
