# Generated by Django 3.2.2 on 2021-07-17 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_type_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Add Type'),
        ),
        migrations.AlterUniqueTogether(
            name='type',
            unique_together={('service', 'name')},
        ),
    ]
