# Generated by Django 3.2.5 on 2021-07-28 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20210717_0734'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Title')),
                ('email', models.EmailField(max_length=254, verbose_name='E-Mail Address')),
                ('message', models.TextField(verbose_name='Message')),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
